### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PaulSup06** [PaulSup06/projet-nsi-rpg#1]
## TODO :
- [x] #3
- [x] Menu au démarrage du jeu
- [x] Menu choix des touches (codage des touches dynamique)
- [x] Joueur:
    - [x] animations
    - [x] attaques
    - [x] inventaire ? (optionnel)
- [x] UI:
    - [x] vie/armure/items
    - [x] Menu de dialogues
- [x] Textures :
    - [x] Joueur (animations)
    - [x] Monde 
    - [x] Mobs
    - [ ] Armes (optionnel textures sur le joueur)
- [x] Entités (mobs et interactions joueur):
    - [x] Mobs agressifs de base (déplacements en ligne)
    - [x] Mobs agressifs intelligents (pathfinding)
    - [ ] Mobs tir à distance ?
    - [x] Autres personnages interactifs (menu ? + dialogues + cinématiques ? + quêtes ?)
- [x] Génération du/des mondes :
    - [x] Convertion fichiers csv en python
    - [x] décodage des csv et génération map
    - [ ] ajout items/mobs dynamiquement (modification du csv ?) (optionnel)
- [x] Ajout énigmes via pages Internet
- [x] Sauvegarde de la position du joueur/son monde actuel à la fermeture du jeu 

#### Ajouter ici (ou dans le Readme) tout lien relatif au projet ou qui pourrait être utile
-Police d'écriture des menus pygame : https://dennisbusch-de.itch.io/0xdbs-terminal-chonker-8x8-1bpp-bitmap-font
